const UPLOAD_PRESET = process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
const API_KEY = process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY
const CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUDNAME

export {
  UPLOAD_PRESET,
  API_KEY,
  CLOUD_NAME
}
